version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    
    commands:
      - sudo apt-get update && sudo apt-get install -y apt-transport-https 
      - wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb 
      - sudo dpkg -i packages-microsoft-prod.deb 
      - sudo apt-get update 
      - sudo apt-get install -y dotnet-sdk-6.0
      - echo Installing Amazon Lambda Templates. Date - `date`
      - dotnet new -i Amazon.Lambda.Templates::*

      - echo Installing Amazon Lambda Tools. Date - `date`
      - dotnet tool install -g Amazon.Lambda.Tools

  pre_build:
    commands:
      # - echo Downloading and installing Sonarqube
      # - mkdir /downloads/sonarqube -p
      # - cd /downloads/sonarqube
      # - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
      # - unzip sonar-scanner-cli-4.2.0.1873-linux.zip
      # - mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
      # - echo -e "sonar.host.url=http://zaomrtfv005:9000/ \n  sonar.sourceEncoding=UTF-8 \n sonar.qualitygate.wait=true " >> /opt/sonar-scanner/conf/sonar-scanner.properties
      # - echo -e "#/bin/bash \n export PATH='$PATH:/opt/sonar-scanner/bin'" >> /etc/profile.d/sonar-scanner.sh
      # - source /etc/profile.d/sonar-scanner.sh
      # - sonar-scanner -v

      - echo Restoring packages. Date - `date`
      - dotnet restore AdeEnablement.Lambda.ClientListOrganisation

  build:
    commands:
    #   - echo Run SonarQube scanner
    #   - sonar-scanner -Dsonar.projectKey=mom-dae-nonprod -Dsonar.sources=. -Dsonar.host.url=http://zaomrtfv005:9900/ -Dsonar.login=f579e85c6c5c1777364517b382550be56578b36f

      - echo Building solution. Date - `date`
      - dotnet build AdeEnablement.Lambda.ClientListOrganisation --no-restore

      - echo Running tests. Date - `date`
      - dotnet test AdeEnablement.Lambda.ClientListOrganisation --no-build

      - mkdir artifacts
      - mkdir artifacts/nonprod

      - echo packaging lambda function. Date - `date`
      - dotnet lambda package --project-location **/src/AdeEnablement.Lambda.ClientListOrganisation --output-package artifacts/nonprod/AdeEnablement.Lambda.ClientListOrganisation.zip

post_build: 
  commands: 
    - echo Copy artifact to S3 bucket
    - aws s3 cp artifacts/nonprod/dae-client-list-organisation.zip s3://dae-client-list-organisation-artifacts-bucket --acl public-read --cache-control "max-age=100"

artifacts:
  files:
    - artifacts/**/*
    - deployment.yml
    