version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    
    commands:

      - sudo apt-get update && sudo apt-get install -y apt-transport-https 
      - wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb 
      - sudo dpkg -i packages-microsoft-prod.deb 
      - sudo apt-get update 
      - sudo apt-get install -y dotnet-sdk-6.0

      - echo Installing Amazon Lambda Templates. Date - `date`
      - dotnet new -i Amazon.Lambda.Templates::*

      - echo Installing Amazon Lambda Tools. Date - `date`
      - dotnet tool install -g Amazon.Lambda.Tools

  build:
    commands:
      - echo deploying lambda function. Date - `date`
      - dotnet lambda deploy-function --function-name dae-client-list-organisation --package artifacts/nonprod/AdeEnablement.Lambda.ClientListOrganisation.zip --region eu-west-1